### ISSUE TITLE
Additional 'meta' options to expand on scope

### ISSUE THREAD

**Issue by Bucko13** [jaredhanson/passport-oauth2#55]
First off thanks for the work you've done on these strategies! 

I'm working with a custom oAuth2 strategy sub-classed off of this and the Github strategy. Everything works great for basic retrieval of profile information but there are some scopes that require additional authorization parameters in a meta field. The oAuth is for a payment provider Coinbase. This is a sample callback URL they are expecting with the scope and additional parameters:
 ``` 
https://www.coinbase.com/oauth/authorize?
    response_type=code&
    client_id=YOUR_CLIENT_ID&
    redirect_uri=YOUR_CALLBACK_URL&
    scope=wallet:transactions:send&
    meta[send_limit_amount]=50&
    meta[send_limit_currency]=USD&
    meta[send_limit_period]=day
```

I tried a couple different ways to add the parameters, including as just another option parameter and even hardcoding the URL but neither were accepted. I was wondering if you had any recommendations for how to extend this class to accept additional parameters?

**Comment by jaredhanson** [comment]
This can be handled by provider-specific subclasses that implement support for proprietary extensions.  See Google for example: https://github.com/jaredhanson/passport-google-oauth2/blob/master/lib/strategy.js#L126

A CoinbaseStrategy subclass can override `authorizationParams()` in order to set these params.

**Comment by Bucko13** [comment]
Awesome, thanks!
