### ISSUE TITLE
State:true causes fail

### ISSUE THREAD

**Issue by rogueturnip** [jaredhanson/passport-oauth2#88]
I'm trying to enable the state option on my authentication strategy but whenever I set "state:true" it starts failing.  I checked the value of the state that was sent to the authorizationURL and what was received on the callback and both look the same.

Is there anything obvious I should be looking for related to using state?  The documentation is light on this topic.

Thanks!

**Comment by jaredhanson** [comment]
What does it mean to start failing? Can you give a description of the behavior, and what debugging you've done to isolate the issue?

**Comment by rogueturnip** [comment]
I don't have the code in front of me right now to give the code details but in my strategy configuration I was putting in console.logs to show me the accessToken and refreshToken .  The moment I added state:true into the options I was no longer getting to the console logging of these but being redirected to my failureredirect link.

I was unsure how to check where in the module it was causing the redirect.  I went through it and found all the callbacks with the error messages but I'm not sure how to display those.  It seems like the state value isn't matching.  When I remove the failure redirect I get a 403 which only occurs in one place in the module.

Thanks!

**Comment by joh-klein** [comment]
Did you eventually figure out the problem?

The way I did my debugging of a similar issue, I [added three lines at this point](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/state/session.js#L61) which printed `req.session`, `providedState`  and `this._key` to the console. That helped me figuring out, that the sessionKey changed between users and thus a lookup was impossible (#94).

**Comment by xyide** [comment]
Are you trying to use the state parameter like a boolean value to determine whether or not to use state?

The `state` parameter is used to preserve some state object set by the client in the Authorization request and makes it available to the client in the response.  In other words, the value of the state parameter is sent along in the request to the oauth server and it is then sent back to the consumer to be used.  Common usage is to prevent CSRF by validating that the state you sent in the request matches the state received in the response.  In this case, the state shouldn't be something simple like `true`.  If you actually do need to pass along the word true to the authorization server, then you should configure the strategy with `state:'true'` (i.e. pass the value in as a string instead of a boolean.

**Comment by jaredhanson** [comment]
Enhancements to state, including storing application-level state, are available in `passport-oauth2@1.6.0`.  More details are available on the blog: [https://medium.com/passportjs/application-state-in-oauth-2-0-1d94379164e](Application State in OAuth 2.0)

These enhancements should resolve this issue. Closing.
